dist: trusty
language: node_js
node_js:
- '6'
- '8'
- '10'
addons:
  apt:
    packages:
      - google-chrome-stable
before_install:
  - export CHROME_BIN=require('puppeteer').executablePath()
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
notifications:
  slack:
    secure: Fdl/sQMTl86jYN1r1CRRRQRgyFoslvrhkkfnM2JSdx4gODPgyg4nCPSKtU5j9wpSbbkq9A+YBeFv+Suh+xYNviegqa0AZbztydfFzVDS7xw43B/uR9Y4LwaP5Kis1WGuIOHawwFISNO3hTUei6aybKiKKlxvfqrARJaO01+Xxrg=
